Repository OpenDreamProject/OpenDream, pull requests merged in 2025-09, with the labels that each got.

#2383 Add ignore rules to .codecov.yml
  .codecov.yml
Labels: size/XS

#2379 Increase test coverage for `DreamMapManager`
  Content.IntegrationTests/DMProject/Tests/change_area_appearance.dm
  Content.IntegrationTests/DMProject/Tests/change_world_size.dm
Labels: size/S

#2397 Fix decoding the `EnumerateAssoc` opcode
  OpenDreamRuntime/Procs/ProcDecoder.cs
Labels: Runtime, size/S

#2382 Misc DMParser Tests & Fixes
  Content.Tests/DMProject/Tests/Call/call_no_params.dm
  Content.Tests/DMProject/Tests/Dereference/deref_no_ident.dm
  Content.Tests/DMProject/Tests/Procs/pick_no_arg.dm
  Content.Tests/DMProject/Tests/SetStatements/no_identifier.dm
  Content.Tests/DMProject/Tests/Statements/ControlFlow/goto_no_label.dm
  Content.Tests/DMProject/Tests/Statements/ControlFlow/trycatch_no_body.dm
  Content.Tests/DMProject/Tests/Statements/Switch/no_cases.dm
  Content.Tests/DMProject/Tests/Statements/Switch/no_expression.dm
  Content.Tests/DMProject/Tests/Statements/Switch/no_upper_limit.dm
  Content.Tests/DMProject/Tests/Statements/While/do_while_no_body1.dm
  Content.Tests/DMProject/Tests/Statements/While/do_while_no_body2.dm
  Content.Tests/DMProject/Tests/Statements/While/while_no_body.dm
  Content.Tests/DMProject/Tests/Tree/upward_search_no_path.dm
  DMCompiler/Compiler/DM/DMParser.cs
  DMCompiler/DM/Builders/DMProcBuilder.cs
Labels: Compiler, size/L

#2372 Remove all `/atom`s from tests
  Content.Tests/DMProject/Tests/Builtins/LocateIn.dm
  Content.Tests/DMProject/Tests/Builtins/__PROC__.dm
  Content.Tests/DMProject/Tests/Builtins/__TYPE__.dm
  Content.Tests/DMProject/Tests/Builtins/gradient.dm
  Content.Tests/DMProject/Tests/Builtins/isnull.dm
  Content.Tests/DMProject/Tests/Const/Const4.dm
  Content.Tests/DMProject/Tests/Const/Const5.dm
  Content.Tests/DMProject/Tests/Const/Const_LateDefinition.dm
  Content.Tests/DMProject/Tests/Const/StaticEqualsConstVar.dm
  Content.Tests/DMProject/Tests/Dereference/Deref1.dm
  Content.Tests/DMProject/Tests/Dereference/Deref2.dm
  Content.Tests/DMProject/Tests/Dereference/Deref3.dm
  Content.Tests/DMProject/Tests/Dereference/Shared/DerefTests.dm
  Content.Tests/DMProject/Tests/Dereference/SrcAssignment.dm
  Content.Tests/DMProject/Tests/Expression/Derefs/assignment_deref.dm
  Content.Tests/DMProject/Tests/Expression/Derefs/by_string_index.dm
  Content.Tests/DMProject/Tests/Expression/Derefs/direct2lax/lax_chain.dm
  Content.Tests/DMProject/Tests/Expression/Derefs/direct2lax/list.dm
  Content.Tests/DMProject/Tests/Expression/Derefs/direct2lax/list_chain.dm
  Content.Tests/DMProject/Tests/Expression/Derefs/direct2lax/objproc.dm
  Content.Tests/DMProject/Tests/Expression/Derefs/direct2lax/topproc.dm
  Content.Tests/DMProject/Tests/Expression/proccall_parent_pass.dm
  Content.Tests/DMProject/Tests/List/ListNullObj.dm
  Content.Tests/DMProject/Tests/List/ListObjVarDecl.dm
  Content.Tests/DMProject/Tests/List/ListVarDecl.dm
  Content.Tests/DMProject/Tests/Operators/double_ternary_cond.dm
  Content.Tests/DMProject/Tests/Operators/logical_assign.dm
  Content.Tests/DMProject/Tests/Operators/output_string.dm
  Content.Tests/DMProject/Tests/Preprocessor/vardecl_define_clash.dm
  Content.Tests/DMProject/Tests/SpecialProcs/initial/initial_list_idx.dm
  Content.Tests/DMProject/Tests/SpecialProcs/initial/initial_vars_index.dm
  Content.Tests/DMProject/Tests/SpecialProcs/issaved/issaved_list_idx.dm
  Content.Tests/DMProject/Tests/SpecialProcs/issaved/issaved_vars_index.dm
  Content.Tests/DMProject/Tests/SpecialProcs/locate/tag_deleted_obj.dm
  Content.Tests/DMProject/Tests/SpecialProcs/locate/tag_empty_string.dm
  Content.Tests/DMProject/Tests/SpecialProcs/locate/tag_nulled.dm
  Content.Tests/DMProject/Tests/SpecialProcs/new/newlist.dm
  Content.Tests/DMProject/Tests/Statements/Assign/logical.dm
  Content.Tests/DMProject/Tests/Statements/Assign/logical_assign_to_deref.dm
  Content.Tests/DMProject/Tests/Statements/Switch/const_objvar.dm
  Content.Tests/DMProject/Tests/Stdlib/Array/list_var_in_obj.dm
  Content.Tests/DMProject/Tests/Stdlib/Array/multidim.dm
  Content.Tests/DMProject/Tests/Stdlib/Array/obj_var_decl.dm
  Content.Tests/DMProject/Tests/Stdlib/List/deref_assoc.dm
  Content.Tests/DMProject/Tests/Stdlib/file_in_var_decl.dm
  Content.Tests/DMProject/Tests/Text/ref.dm
  Content.Tests/DMProject/Tests/Tree/Const/deref_as_const.dm
  Content.Tests/DMProject/Tests/Tree/Const/init_from_obj_var.dm
  Content.Tests/DMProject/Tests/Tree/Const/sort_const_initialize.dm
  Content.Tests/DMProject/Tests/Tree/Global/StaticScope/scope1.dm
  Content.Tests/DMProject/Tests/Tree/Global/StaticScope/scope4.dm
  Content.Tests/DMProject/Tests/Tree/Global/StaticScope/scope_in_assoc_list.dm
  Content.Tests/DMProject/Tests/Tree/Global/StaticScope/static_list.dm
  Content.Tests/DMProject/Tests/Tree/Global/StaticScope/static_proc.dm
  Content.Tests/DMProject/Tests/Tree/Global/StaticScope/static_vars.dm
  Content.Tests/DMProject/Tests/Tree/Global/Var/global_chain_call.dm
  Content.Tests/DMProject/Tests/Tree/Override/override_double.dm
  Content.Tests/DMProject/Tests/Tree/Override/override_first.dm
  Content.Tests/DMProject/Tests/Tree/keyword_type.dm
  Content.Tests/DMProject/Tests/Tree/proc_and_var.dm
Labels: size/L
